"""Copy experiment evidence into a results repository (read-only on the source).

An experiment is described by ``experiments/<id>/experiment.json`` in this repository
(run ids, roles, provenance notes) plus hand-written ``README.md`` and ``protocol.md``.
``export_experiment`` writes::

    <dest>/README.md                         index of all exported experiments
    <dest>/ledger-snapshots/ledger-<sha12>.json   historical ledger copies
    <dest>/experiments/<id>/
        README.md, protocol.md               copied from this repository
        manifest.json                        runs, roles, settings, provenance, checksums
        report.md                            generated by clm_lib.report
        metrics.json, metrics.csv            per-run machine-readable metrics
        SHA256SUMS                           every file in the experiment directory
        artifacts/runs/<role>/<run_id>/      run evidence (fixtures exported separately)
        artifacts/fixtures/<task>/           task files, verified against each run's copy
        artifacts/comparisons/               comparison records (+ frozen-source patches)
        artifacts/source/                    source patches named in experiment.json

Run evidence is never silently replaced: if a run directory already exists in the
destination with different content, the export stops with ``ExportConflict``.
Raw runs, the active ledger and the source tree are only read.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import stat
from pathlib import Path
from typing import Any

from . import __version__
from .report import build_report, rescore
from .tasks import SCORER_VERSION, generate

EXPORT_FORMAT = "clm-results-export/1"
ROLES = ("evaluation", "guided", "calibration", "smoke", "access-failure")
REDACTIONS = [
    {
        "file": "run.json",
        "field": "executor.user",
        "replacement": "<host uid:gid> (non-root)",
        "reason": "local account id; not needed to interpret the run",
    }
]
SKIP_NAMES = {".context.json.host-tmp"}


class ExportConflict(RuntimeError):
    """Destination already holds different evidence under the same name."""


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _redact(rel: str, data: bytes) -> bytes:
    if rel != "run.json":
        return data
    doc = json.loads(data)
    if isinstance(doc.get("executor"), dict) and "user" in doc["executor"]:
        doc["executor"]["user"] = REDACTIONS[0]["replacement"]
    return (json.dumps(doc, indent=1, ensure_ascii=False) + "\n").encode()


def collect(src: Path, skip_top: frozenset[str] = frozenset()) -> dict[str, bytes]:
    """Regular files under src (relative path -> bytes), refusing symlinks."""
    out: dict[str, bytes] = {}
    for dirpath, dirnames, filenames in os.walk(src, followlinks=False):
        rel_dir = os.path.relpath(dirpath, src)
        if rel_dir == ".":
            dirnames[:] = sorted(d for d in dirnames if d not in skip_top)
        else:
            dirnames.sort()
        for name in sorted(filenames):
            full = Path(dirpath, name)
            st = os.lstat(full)
            if stat.S_ISLNK(st.st_mode):
                raise ExportConflict(f"refusing to export symlink {full}")
            if name in SKIP_NAMES or not stat.S_ISREG(st.st_mode):
                continue
            rel = os.path.relpath(full, src)
            out[rel] = _redact(rel, full.read_bytes())
    return out


def sums_text(files: dict[str, bytes]) -> str:
    return "".join(f"{_sha(files[k])}  {k}\n" for k in sorted(files))


def write_tree(dest: Path, files: dict[str, bytes]) -> str:
    """Write files plus SHA256SUMS; 'written' / 'unchanged'; conflict if different."""
    text = sums_text(files)
    marker = dest / "SHA256SUMS"
    if dest.exists():
        if marker.exists() and marker.read_text() == text:
            return "unchanged"
        raise ExportConflict(
            f"{dest} exists with different content; refusing to overwrite evidence"
        )
    for rel, data in files.items():
        p = dest / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
    marker.write_text(text)
    return "written"


def fixture_dir_sha(root: Path) -> str:
    """Same algorithm as TaskInstance.fixture_sha256, over files on disk."""
    h = hashlib.sha256()
    files = sorted(
        str(p.relative_to(root)) for p in root.rglob("*") if p.is_file() and not p.is_symlink()
    )
    for rel in files:
        h.update(rel.encode())
        h.update(b"\0")
        h.update((root / rel).read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def _load(p: Path) -> Any:
    return json.loads(p.read_text(encoding="utf-8"))


def _write_if_changed(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return "unchanged"
    status = "updated" if path.exists() else "written"
    path.write_text(text, encoding="utf-8")
    return status


def _metrics_row(run_id: str, role: str, src: Path, charged: float) -> dict[str, Any]:
    row: dict[str, Any] = {"run_id": run_id, "role": role, "ledger_charged_usd": round(charged, 6)}
    if not (src / "summary.json").exists():
        return row
    m = _load(src / "summary.json")
    c, s = m["counts"], m["score"]
    rs = rescore(src)
    row.update(
        mode=m["mode"],
        task=m["task"],
        status=m["status"],
        valid_for_comparison=m["valid_for_comparison"],
        outcome_recorded=s["outcome"],
        strict_recorded=s["strict_success"],
        scorer_recorded=_load(src / "evaluator" / "score.json").get("scorer_version", "score/1"),
        outcome_current=rs["outcome"] if rs else "no_answer",
        strict_current=bool(rs and rs["strict_success"]),
        scorer_current=SCORER_VERSION,
        cause_ok=bool(rs and rs["cause_ok"]),
        remedy_ok=bool(rs and rs["remedy_ok"]),
        value_status=rs["value_status"] if rs else "missing",
        evidence_groups=json.dumps(rs["groups_covered"] if rs else {}),
        provider_calls=c["provider_calls"],
        action_calls=c["action_calls"],
        repair_calls=c["repair_calls"],
        summary_calls=c["summary_calls"],
        api_retries=c["api_retries"],
        executions=c["executions"],
        edit_attempts=c["edit_attempts"],
        edits_accepted_changed=c["edits_accepted_changed"],
        edits_rejected=c["edits_rejected"],
        summaries_applied=c["summaries_applied"],
        recovery_requests=c["recovery_requests"],
        pressure_steps=c["pressure_steps"],
        input_tokens=m["usage_provider_reported"]["input_tokens_uncached"],
        output_tokens=m["usage_provider_reported"]["output_tokens"],
        peak_request_input_tokens=m["peak_request_input_tokens_reported"],
        cost_usd=m["cost"]["incurred_usd"],
        elapsed_s=m["elapsed_s"],
        prompt_version=m.get("prompt_version"),
        fixture_sha256=m.get("fixture_sha256"),
    )
    for k, v in (m.get("management") or {}).items():
        row[f"mgmt_{k}"] = json.dumps(v) if isinstance(v, (dict, list)) else v
    return row


def export_experiment(
    exp_dir: Path, runs_root: Path, ledger_path: Path, dest_root: Path
) -> dict[str, Any]:
    spec = _load(exp_dir / "experiment.json")
    exp_id = spec["id"]
    out = dest_root / "experiments" / exp_id
    art = out / "artifacts"
    log: dict[str, Any] = {"experiment": exp_id, "runs": {}, "fixtures": {}, "derived": {}}

    ledger = _load(ledger_path)
    ledger_text = json.dumps(ledger, indent=1, ensure_ascii=False) + "\n"
    ledger_sha = _sha(ledger_text.encode())
    snap_rel = f"ledger-snapshots/ledger-{ledger_sha[:12]}.json"
    snap = dest_root / snap_rel
    if not snap.exists():
        snap.parent.mkdir(parents=True, exist_ok=True)
        snap.write_text(ledger_text, encoding="utf-8")
    charged: dict[str, float] = {}
    for e in ledger["entries"]:
        charged[e["run_id"]] = charged.get(e["run_id"], 0.0) + float(e["charged_usd"])

    runs_meta = []
    rows = []
    tasks: dict[str, str] = {}
    for r in spec["runs"]:
        rid, role = r["run_id"], r["role"]
        if role not in ROLES:
            raise ValueError(f"unknown role {role!r} for {rid}")
        src = runs_root / rid
        files = collect(src, skip_top=frozenset({"fixtures"}))
        status = write_tree(art / "runs" / role / rid, files)
        log["runs"][rid] = status
        meta: dict[str, Any] = {
            "run_id": rid,
            "role": role,
            "note": r.get("note", ""),
            "artifact_path": f"artifacts/runs/{role}/{rid}",
            "sha256sums_sha256": _sha(sums_text(files).encode()),
            "files": len(files),
            "ledger_charged_usd": round(charged.get(rid, 0.0), 6),
        }
        if (src / "run.json").exists():
            rj = _load(src / "run.json")
            meta.update(
                mode=rj["mode"],
                task=rj["task"],
                prompt_version=rj["prompt_version"],
                generator_version=rj["generator_version"],
                fixture_seed=rj["fixture_seed"],
                fixture_sha256=rj["fixture_sha256"],
                model=rj["provider"]["model"],
                effort=rj["provider"].get("effort"),
                started=rj["started"],
            )
            if (src / "fixtures").exists():
                on_disk = fixture_dir_sha(src / "fixtures")
                inst = generate(rj["task"])
                released = None
                if inst.staged and (src / "summary.json").exists():
                    released = _load(src / "summary.json")["management"]["stages_released"]
                    meta["stages_released"] = released
                meta["fixtures_on_disk_sha256"] = on_disk
                meta["fixtures_match_generator"] = on_disk == inst.sha_upto(released)
                tasks[rj["task"]] = rj["fixture_sha256"]
        runs_meta.append(meta)
        rows.append(_metrics_row(rid, role, src, charged.get(rid, 0.0)))

    for task, expected in sorted(tasks.items()):
        inst = generate(task)
        if inst.fixture_sha256 != expected:
            raise ExportConflict(f"generator output for {task} no longer matches recorded fixtures")
        files = {k: v.encode() for k, v in inst.files.items()}
        log["fixtures"][task] = write_tree(art / "fixtures" / task, files)

    comps_meta = []
    for name in spec.get("comparisons", []):
        files = {}
        for suffix in (".json", ".patch"):
            p = runs_root / "comparisons" / f"{name}{suffix}"
            if p.exists():
                files[p.name] = p.read_bytes()
        log["derived"][f"comparison {name}"] = write_tree(art / "comparisons" / name, files)
        comp = _load(runs_root / "comparisons" / f"{name}.json")
        comps_meta.append(
            {
                "comparison": name,
                "artifact_path": f"artifacts/comparisons/{name}",
                "frozen": comp.get("frozen"),
                "halted": comp.get("halted"),
                "cells": len(comp["cells"]),
                "missing": sum(1 for c in comp["cells"] if c["status"] == "missing"),
            }
        )

    if spec.get("source_patches"):
        files = {Path(p).name: (exp_dir / p).read_bytes() for p in spec["source_patches"]}
        log["derived"]["source patches"] = write_tree(art / "source", files)

    for doc in ("README.md", "protocol.md"):
        log["derived"][doc] = _write_if_changed(
            out / doc, (exp_dir / doc).read_text(encoding="utf-8")
        )

    report = build_report(
        runs_root,
        ledger_path,
        run_dirs=[runs_root / r["run_id"] for r in spec["runs"]],
        comparisons=[runs_root / "comparisons" / f"{n}.json" for n in spec.get("comparisons", [])],
        title=f"{exp_id}: generated report",
    )
    log["derived"]["report.md"] = _write_if_changed(out / "report.md", report)
    log["derived"]["metrics.json"] = _write_if_changed(
        out / "metrics.json", json.dumps(rows, indent=1, ensure_ascii=False) + "\n"
    )
    keys: list[str] = []
    for row in rows:
        keys += [k for k in row if k not in keys]
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=keys, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    log["derived"]["metrics.csv"] = _write_if_changed(out / "metrics.csv", buf.getvalue())

    manifest = {
        "format": EXPORT_FORMAT,
        "experiment": exp_id,
        "title": spec["title"],
        "status": spec.get("status", ""),
        "exported_with": {"clm_lib_version": __version__, "current_scorer": SCORER_VERSION},
        "provenance": spec.get("provenance", {}),
        "settings": spec.get("settings", {}),
        "runs": runs_meta,
        "comparisons": comps_meta,
        "fixtures": {t: {"sha256": s, "path": f"artifacts/fixtures/{t}"} for t, s in sorted(tasks.items())},
        "ledger_snapshot": {"path": f"../../{snap_rel}", "sha256": ledger_sha,
                            "note": "historical copy; the active ledger stays in the clm-lib repo"},
        "redactions": REDACTIONS,
        "excluded": [
            "credential files and environment (never present in run artifacts)",
            "request headers (never recorded)",
            "per-run fixtures/ copies (exported once per task under artifacts/fixtures, hash-verified)",
        ],
    }  # fmt: skip
    log["derived"]["manifest.json"] = _write_if_changed(
        out / "manifest.json", json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"
    )
    every = {
        str(p.relative_to(out)): p.read_bytes()
        for p in sorted(out.rglob("*"))
        if p.is_file() and p != out / "SHA256SUMS"
    }
    (out / "SHA256SUMS").write_text(sums_text(every))
    write_index(dest_root)
    return log


def write_index(dest_root: Path) -> None:
    rows = []
    for m in sorted((dest_root / "experiments").glob("*/manifest.json")):
        man = _load(m)
        rows.append(
            f"| [{man['experiment']}](experiments/{man['experiment']}/README.md) | {man['title']} | {man['status']} |"
        )
    text = INDEX_TEMPLATE.replace("{rows}", "\n".join(rows))
    _write_if_changed(dest_root / "README.md", text)


INDEX_TEMPLATE = """# clm-lib test results

Evidence from experiments run with [clm-lib](https://github.com/armalite/clm-lib), an experimental
library where a model edits its own working context through code ("context as a file", inspired by
Context Language Models).

This repository is generated by `clm-lib export` and hand-written experiment notes. Raw run
directories are copied unchanged except for the redactions listed in each manifest.

## Experiments

| Experiment | Question | Status |
| --- | --- | --- |
{rows}

## How to navigate an experiment

- `README.md`: the question, setup, outcome and limitations, in plain language.
- `protocol.md`: what was planned before running, and what changed afterwards.
- `report.md`: generated tables (per-run results, context-edit evidence, comparison aggregates).
- `metrics.json` / `metrics.csv`: one row per run, machine-readable.
- `manifest.json`: run ids and roles, settings, source provenance, fixture and ledger checksums.
- `artifacts/runs/<role>/<run_id>/`: the evidence for one run. Roles: `evaluation` (comparison
  runs), `guided` (explicitly prompted demonstrations), `calibration` (development runs used to
  choose settings), `smoke` and `access-failure` (connectivity checks).
  - `run.json`: configuration; `events.jsonl`: chronological event log; `requests/`: exact
    model requests (no headers); `context/`: accepted context revisions and diffs;
    `scripts/`: model-written code, saved before it ran; `files/`: workspace files (helpers)
    before/after each step; `workspace/`: final sandbox workspace; `evaluator/`: ground truth
    and score (written after the run); `summary.json`: metrics.
- `artifacts/fixtures/<task>/`: the task files the agent investigated.
- `SHA256SUMS`: checksums of every file in the experiment directory.
- `ledger-snapshots/`: historical copies of the spend ledger (the active one lives in clm-lib).
"""
