"""Copy experiment evidence into a results repository (read-only on the source).

Ownership:

- clm-lib (this repository) owns the *selection* of an experiment:
  ``experiments/<id>/experiment.json`` (run ids, roles, settings, provenance notes).
- The results repository owns every human-written document: the root ``README.md`` and,
  per experiment, ``README.md``, ``SUMMARY.md`` and ``protocol.md``. The exporter never
  overwrites these. If one is missing, it creates a generic starter (or, for a first export,
  copies one found next to ``experiment.json``) and reports that it did so.
- The exporter owns everything it generates: evidence trees, ``manifest.json``,
  ``report.md``, ``metrics.json``, ``metrics.csv``, ``SHA256SUMS`` and the root
  ``EXPORT_FORMAT.md``.

``export_experiment`` writes::

    <dest>/README.md                         human-maintained index (starter only if missing)
    <dest>/EXPORT_FORMAT.md                  generated: layout, ownership, checksum policy
    <dest>/ledger-snapshots/ledger-<sha12>.json   historical ledger copies
    <dest>/experiments/<id>/
        README.md, SUMMARY.md, protocol.md   human-maintained (starter only if missing)
        manifest.json                        generated: runs, roles, settings, provenance
        report.md                            generated by clm_lib.report
        metrics.json, metrics.csv            generated per-run metrics
        SHA256SUMS                           generated: evidence + generated files only
        artifacts/runs/<role>/<run_id>/      immutable run evidence (own SHA256SUMS)
        artifacts/fixtures/<task>/           immutable task files (own SHA256SUMS)
        artifacts/comparisons/<stamp>/       immutable comparison records (own SHA256SUMS)
        artifacts/source/                    immutable provenance patches (own SHA256SUMS)

Checksums: every immutable tree carries its own ``SHA256SUMS``, and a different tree under
an existing name raises ``ExportConflict``. The experiment-level ``SHA256SUMS`` excludes
the human-maintained documents, so editing a write-up never looks like corrupted evidence.
Before it is rewritten, its existing entries for ``artifacts/`` are re-verified, and any
mismatch also raises ``ExportConflict``. Raw runs, the active ledger and the source tree are
only read.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import stat
from pathlib import Path
from typing import Any

from . import __version__
from .report import build_report, rescore
from .tasks import SCORER_VERSION, generate

EXPORT_FORMAT = "clm-results-export/1"
ROLES = ("evaluation", "guided", "calibration", "smoke", "access-failure")
REDACTIONS = [
    {
        "file": "run.json",
        "field": "executor.user",
        "replacement": "<host uid:gid> (non-root)",
        "reason": "local account id; not needed to interpret the run",
    }
]
SKIP_NAMES = {".context.json.host-tmp"}
HUMAN_DOCS = ("README.md", "SUMMARY.md", "protocol.md")  # destination-owned, never overwritten
GENERATED_FILES = ("manifest.json", "report.md", "metrics.json", "metrics.csv")
SUMS_HEADER = (
    "# Generated by clm-lib export. Covers immutable evidence (artifacts/) and generated files\n"
    "# (manifest.json, report.md, metrics.*). Human-maintained documents (README.md, SUMMARY.md,\n"
    "# protocol.md) are deliberately excluded and may be edited freely.\n"
)


class ExportConflict(RuntimeError):
    """Destination already holds different evidence under the same name."""


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _redact(rel: str, data: bytes) -> bytes:
    if rel != "run.json":
        return data
    doc = json.loads(data)
    if isinstance(doc.get("executor"), dict) and "user" in doc["executor"]:
        doc["executor"]["user"] = REDACTIONS[0]["replacement"]
    return (json.dumps(doc, indent=1, ensure_ascii=False) + "\n").encode()


def collect(src: Path, skip_top: frozenset[str] = frozenset()) -> dict[str, bytes]:
    """Regular files under src (relative path -> bytes), refusing symlinks."""
    out: dict[str, bytes] = {}
    for dirpath, dirnames, filenames in os.walk(src, followlinks=False):
        rel_dir = os.path.relpath(dirpath, src)
        if rel_dir == ".":
            dirnames[:] = sorted(d for d in dirnames if d not in skip_top)
        else:
            dirnames.sort()
        for name in sorted(filenames):
            full = Path(dirpath, name)
            st = os.lstat(full)
            if stat.S_ISLNK(st.st_mode):
                raise ExportConflict(f"refusing to export symlink {full}")
            if name in SKIP_NAMES or not stat.S_ISREG(st.st_mode):
                continue
            rel = os.path.relpath(full, src)
            out[rel] = _redact(rel, full.read_bytes())
    return out


def sums_text(files: dict[str, bytes]) -> str:
    return "".join(f"{_sha(files[k])}  {k}\n" for k in sorted(files))


def write_tree(dest: Path, files: dict[str, bytes]) -> str:
    """Write files plus SHA256SUMS; 'written' / 'unchanged'; conflict if different.

    "unchanged" requires both the recorded SHA256SUMS and the actual files on disk to match
    the expected evidence; a missing, modified or extra file is a conflict.
    """
    text = sums_text(files)
    marker = dest / "SHA256SUMS"
    if dest.exists():
        if not (marker.exists() and marker.read_text() == text):
            raise ExportConflict(
                f"{dest} exists with different content; refusing to overwrite evidence"
            )
        on_disk = {str(p.relative_to(dest)) for p in dest.rglob("*") if p.is_file() and p != marker}
        for rel, data in files.items():
            path = dest / rel
            if not path.is_file():
                raise ExportConflict(f"recorded evidence file {path} is missing")
            if path.read_bytes() != data:
                raise ExportConflict(
                    f"evidence file {path} no longer matches its recorded checksum"
                )
        extra = sorted(on_disk - set(files))
        if extra:
            raise ExportConflict(f"{dest} contains unrecorded files: {extra[:5]}")
        return "unchanged"
    for rel, data in files.items():
        p = dest / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
    marker.write_text(text)
    return "written"


def fixture_dir_sha(root: Path) -> str:
    """Same algorithm as TaskInstance.fixture_sha256, over files on disk."""
    h = hashlib.sha256()
    files = sorted(
        str(p.relative_to(root)) for p in root.rglob("*") if p.is_file() and not p.is_symlink()
    )
    for rel in files:
        h.update(rel.encode())
        h.update(b"\0")
        h.update((root / rel).read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def _load(p: Path) -> Any:
    return json.loads(p.read_text(encoding="utf-8"))


def _write_if_changed(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return "unchanged"
    status = "updated" if path.exists() else "written"
    path.write_text(text, encoding="utf-8")
    return status


def _metrics_row(run_id: str, role: str, src: Path, charged: float) -> dict[str, Any]:
    row: dict[str, Any] = {"run_id": run_id, "role": role, "ledger_charged_usd": round(charged, 6)}
    if not (src / "summary.json").exists():
        return row
    m = _load(src / "summary.json")
    c, s = m["counts"], m["score"]
    rs = rescore(src)
    row.update(
        mode=m["mode"],
        task=m["task"],
        status=m["status"],
        valid_for_comparison=m["valid_for_comparison"],
        outcome_recorded=s["outcome"],
        strict_recorded=s["strict_success"],
        scorer_recorded=_load(src / "evaluator" / "score.json").get("scorer_version", "score/1"),
        outcome_current=rs["outcome"] if rs else "no_answer",
        strict_current=bool(rs and rs["strict_success"]),
        scorer_current=SCORER_VERSION,
    )
    if rs and "by_category" in rs:  # coding task
        row["scorer_current"] = rs.get("scorer_version", row["scorer_current"])
        row.update(
            completed=rs["completed"],
            checks_total=rs["checks"],
            checks_passed=rs["passed"],
            stale_checks=rs["stale"],
            import_error=rs["import_error"],
            evaluation_error=rs.get("evaluation_error"),
        )
        if "retained_rule_failures" in rs:  # invoice-checks/2
            row.update(
                retained_rule_failures=rs["retained_rule_failures"],
                retained_failed_modules=json.dumps(rs["retained_failed_modules"]),
                regressions=json.dumps(rs["regressions"]),
                stale_modules=json.dumps(rs["stale_modules"]),
                boundary_passed=rs["boundary"]["passed"],
                boundary_total=rs["boundary"]["total"],
                type_errors=rs["type_errors"],
            )
        for cat, v in sorted(rs["by_category"].items()):
            row[f"{cat}_passed"], row[f"{cat}_total"], row[f"{cat}_stale"] = (
                v["passed"],
                v["total"],
                v["stale"],
            )
    else:
        row.update(
            cause_ok=bool(rs and rs["cause_ok"]),
            remedy_ok=bool(rs and rs["remedy_ok"]),
            value_status=rs["value_status"] if rs else "missing",
            evidence_groups=json.dumps(rs["groups_covered"] if rs else {}),
        )
    row.update(
        provider_calls=c["provider_calls"],
        action_calls=c["action_calls"],
        repair_calls=c["repair_calls"],
        summary_calls=c["summary_calls"],
        api_retries=c["api_retries"],
        executions=c["executions"],
        edit_attempts=c["edit_attempts"],
        edits_accepted_changed=c["edits_accepted_changed"],
        edits_rejected=c["edits_rejected"],
        summaries_applied=c["summaries_applied"],
        recovery_requests=c["recovery_requests"],
        pressure_steps=c["pressure_steps"],
        input_tokens=m["usage_provider_reported"]["input_tokens_uncached"],
        output_tokens=m["usage_provider_reported"]["output_tokens"],
        peak_request_input_tokens=m["peak_request_input_tokens_reported"],
        cost_usd=m["cost"]["incurred_usd"],
        elapsed_s=m["elapsed_s"],
        prompt_version=m.get("prompt_version"),
        fixture_sha256=m.get("fixture_sha256"),
    )
    rq = m.get("request") or {}
    u = m["usage_provider_reported"]
    row.update(
        # Request layout and caching condition (single-user/1 and off before experiment 006).
        request_layout=rq.get("layout", "single-user/1"),
        prompt_caching=rq.get("prompt_caching", "off"),
        cache_ttl=rq.get("cache_ttl"),
        run_isolation=rq.get("run_isolation", "none"),
        cache_read_input_tokens=u.get("cache_read_input_tokens", 0),
        cache_creation_input_tokens=u.get("cache_creation_input_tokens", 0),
        first_call_cache_read_tokens=(rq.get("first_call_cache") or {}).get(
            "cache_read_input_tokens"
        ),
        provider_latency_s=rq.get("provider_latency_s"),
    )
    for kind, k in sorted((rq.get("by_kind") or {}).items()):
        row[f"{kind}_cost_usd"] = k["cost_usd"]
        row[f"{kind}_cache_read_tokens"] = k["cache_read_input_tokens"]
        row[f"{kind}_cache_creation_tokens"] = k["cache_creation_input_tokens"]
        row[f"{kind}_uncached_input_tokens"] = k["input_tokens_uncached"]
        row[f"{kind}_latency_s"] = k["latency_s"]
    for k, v in (m.get("management") or {}).items():
        row[f"mgmt_{k}"] = json.dumps(v) if isinstance(v, (dict, list)) else v
    return row


def current_scorer(rows: list[dict[str, Any]]) -> str | list[str]:
    """The scorer(s) behind the exported rows' current scores: one version, or a sorted list
    when the selection mixes task kinds."""
    found = sorted({r["scorer_current"] for r in rows if r.get("scorer_current")})
    if not found:
        return SCORER_VERSION
    return found[0] if len(found) == 1 else found


def export_experiment(
    exp_dir: Path, runs_root: Path, ledger_path: Path, dest_root: Path
) -> dict[str, Any]:
    spec = _load(exp_dir / "experiment.json")
    exp_id = spec["id"]
    out = dest_root / "experiments" / exp_id
    art = out / "artifacts"
    log: dict[str, Any] = {
        "experiment": exp_id,
        "runs": {},
        "fixtures": {},
        "derived": {},
        "documents": {},
        "warnings": [],
    }
    # Fail before writing anything if previously exported evidence is missing or altered.
    verify_recorded_evidence(out)

    ledger = _load(ledger_path)
    ledger_text = json.dumps(ledger, indent=1, ensure_ascii=False) + "\n"
    ledger_sha = _sha(ledger_text.encode())
    snap_rel = f"ledger-snapshots/ledger-{ledger_sha[:12]}.json"
    snap = dest_root / snap_rel
    if not snap.exists():
        snap.parent.mkdir(parents=True, exist_ok=True)
        snap.write_text(ledger_text, encoding="utf-8")
    charged: dict[str, float] = {}
    for e in ledger["entries"]:
        charged[e["run_id"]] = charged.get(e["run_id"], 0.0) + float(e["charged_usd"])

    runs_meta = []
    rows = []
    tasks: dict[str, str] = {}
    for r in spec["runs"]:
        rid, role = r["run_id"], r["role"]
        if role not in ROLES:
            raise ValueError(f"unknown role {role!r} for {rid}")
        src = runs_root / rid
        files = collect(src, skip_top=frozenset({"fixtures"}))
        status = write_tree(art / "runs" / role / rid, files)
        log["runs"][rid] = status
        meta: dict[str, Any] = {
            "run_id": rid,
            "role": role,
            "note": r.get("note", ""),
            "artifact_path": f"artifacts/runs/{role}/{rid}",
            "sha256sums_sha256": _sha(sums_text(files).encode()),
            "files": len(files),
            "ledger_charged_usd": round(charged.get(rid, 0.0), 6),
        }
        if (src / "run.json").exists():
            rj = _load(src / "run.json")
            meta.update(
                mode=rj["mode"],
                task=rj["task"],
                prompt_version=rj["prompt_version"],
                generator_version=rj["generator_version"],
                fixture_seed=rj["fixture_seed"],
                fixture_sha256=rj["fixture_sha256"],
                model=rj["provider"]["model"],
                effort=rj["provider"].get("effort"),
                started=rj["started"],
            )
            if (src / "fixtures").exists():
                on_disk = fixture_dir_sha(src / "fixtures")
                inst = generate(rj["task"])
                released = None
                if inst.staged and (src / "summary.json").exists():
                    released = _load(src / "summary.json")["management"]["stages_released"]
                    meta["stages_released"] = released
                meta["fixtures_on_disk_sha256"] = on_disk
                meta["fixtures_match_generator"] = on_disk == inst.sha_upto(released)
                tasks[rj["task"]] = rj["fixture_sha256"]
        runs_meta.append(meta)
        rows.append(_metrics_row(rid, role, src, charged.get(rid, 0.0)))

    for task, expected in sorted(tasks.items()):
        inst = generate(task)
        if inst.fixture_sha256 != expected:
            raise ExportConflict(f"generator output for {task} no longer matches recorded fixtures")
        files = {k: v.encode() for k, v in inst.files.items()}
        log["fixtures"][task] = write_tree(art / "fixtures" / task, files)

    comps_meta = []
    for name in spec.get("comparisons", []):
        files = {}
        for suffix in (".json", ".patch"):
            p = runs_root / "comparisons" / f"{name}{suffix}"
            if p.exists():
                files[p.name] = p.read_bytes()
        log["derived"][f"comparison {name}"] = write_tree(art / "comparisons" / name, files)
        comp = _load(runs_root / "comparisons" / f"{name}.json")
        comps_meta.append(
            {
                "comparison": name,
                "artifact_path": f"artifacts/comparisons/{name}",
                "frozen": comp.get("frozen"),
                "halted": comp.get("halted"),
                "cells": len(comp["cells"]),
                "missing": sum(1 for c in comp["cells"] if c["status"] == "missing"),
            }
        )

    if spec.get("source_patches"):
        files = {}
        for rel in spec["source_patches"]:
            name = Path(rel).name
            local, held = exp_dir / rel, art / "source" / name
            if local.exists():
                files[name] = local.read_bytes()
            elif held.exists():  # provenance already owned by the results repository
                files[name] = held.read_bytes()
            else:
                raise ExportConflict(
                    f"source patch {rel} is in neither clm-lib nor the destination"
                )
        log["derived"]["source patches"] = write_tree(art / "source", files)

    for doc in HUMAN_DOCS:
        log["documents"][doc] = _seed_doc(out / doc, exp_dir / doc, _starter(doc, spec))

    report = build_report(
        runs_root,
        ledger_path,
        run_dirs=[runs_root / r["run_id"] for r in spec["runs"]],
        comparisons=[runs_root / "comparisons" / f"{n}.json" for n in spec.get("comparisons", [])],
        title=f"{exp_id}: generated report",
    )
    log["derived"]["report.md"] = _write_if_changed(out / "report.md", report)
    log["derived"]["metrics.json"] = _write_if_changed(
        out / "metrics.json", json.dumps(rows, indent=1, ensure_ascii=False) + "\n"
    )
    keys: list[str] = []
    for row in rows:
        keys += [k for k in row if k not in keys]
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=keys, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    log["derived"]["metrics.csv"] = _write_if_changed(out / "metrics.csv", buf.getvalue())

    manifest = {
        "format": EXPORT_FORMAT,
        "experiment": exp_id,
        "title": spec["title"],
        "exported_with": {"clm_lib_version": __version__, "current_scorer": current_scorer(rows)},
        "provenance": spec.get("provenance", {}),
        "settings": spec.get("settings", {}),
        "runs": runs_meta,
        "comparisons": comps_meta,
        "fixtures": {
            t: {"sha256": s, "path": f"artifacts/fixtures/{t}"} for t, s in sorted(tasks.items())
        },
        "ledger_snapshot": {
            "path": f"../../{snap_rel}",
            "sha256": ledger_sha,
            "note": "historical copy; the active ledger stays in the clm-lib repo",
        },
        "documents": {
            "human_maintained": [d for d in HUMAN_DOCS if (out / d).exists()],
            "generated": list(GENERATED_FILES),
            "note": "human-maintained documents are owned by the results repository and never overwritten by export",
        },
        "checksum_policy": "artifacts/** trees carry their own SHA256SUMS and are immutable; the experiment SHA256SUMS covers artifacts and generated files and excludes human-maintained documents",
        "redactions": REDACTIONS,
        "excluded": [
            "credential files and environment (never present in run artifacts)",
            "request headers (never recorded)",
            "per-run fixtures/ copies (exported once per task under artifacts/fixtures, hash-verified)",
        ],
    }
    log["derived"]["manifest.json"] = _write_if_changed(
        out / "manifest.json", json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"
    )
    write_evidence_sums(out)
    log["documents"]["root README.md"] = _seed_root(dest_root)
    _write_if_changed(dest_root / "EXPORT_FORMAT.md", EXPORT_FORMAT_DOC)
    if exp_id not in (dest_root / "README.md").read_text(encoding="utf-8"):
        log["warnings"].append(f"root README.md does not mention {exp_id}; add a summary/link")
    return log


def evidence_files(out: Path) -> dict[str, bytes]:
    """Files covered by the experiment-level SHA256SUMS (excludes human documents)."""
    return {
        str(p.relative_to(out)): p.read_bytes()
        for p in sorted(out.rglob("*"))
        if p.is_file()
        and p != out / "SHA256SUMS"
        and not (p.parent == out and p.name in HUMAN_DOCS)
    }


def _read_sums(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if path.exists():
        for line in path.read_text().splitlines():
            if line and not line.startswith("#"):
                digest, rel = line.split("  ", 1)
                out[rel] = digest
    return out


def verify_recorded_evidence(out: Path) -> None:
    """Every artifact recorded in the experiment SHA256SUMS must still exist and match."""
    for rel, digest in _read_sums(out / "SHA256SUMS").items():
        if not rel.startswith("artifacts/"):
            continue  # generated files may legitimately be regenerated
        path = out / rel
        if not path.is_file():
            raise ExportConflict(f"recorded evidence file {rel} is missing")
        if _sha(path.read_bytes()) != digest:
            raise ExportConflict(f"evidence file {rel} no longer matches its recorded checksum")


def write_evidence_sums(out: Path) -> None:
    """Re-verify recorded artifact checksums, then rewrite the experiment SHA256SUMS."""
    verify_recorded_evidence(out)
    (out / "SHA256SUMS").write_text(SUMS_HEADER + sums_text(evidence_files(out)))


def _starter(doc: str, spec: dict[str, Any]) -> str:
    exp_id, title = spec["id"], spec.get("title", spec["id"])
    if doc == "SUMMARY.md":
        return (
            f"### [{exp_id}](experiments/{exp_id}/README.md)\n\n{title}\n\n"
            "_Starter created by clm-lib export: replace with a short summary._\n"
        )
    if doc == "protocol.md":
        return (
            f"# {exp_id}: protocol\n\n_Starter created by clm-lib export. Record what was planned "
            "before running and anything that changed afterwards._\n"
        )
    return (
        f"# {exp_id}\n\n{title}\n\n_Starter created by clm-lib export. This write-up is maintained in "
        "the results repository._\n\n## What problem did we test?\n\n## How did the comparison work?\n\n"
        "## What happened?\n\n## What do the results tell us?\n\n## What remains untested?\n\n"
        "## Where is the evidence?\n\nSee `manifest.json`, `report.md`, `metrics.*` and `artifacts/`.\n"
    )


def _seed_doc(dest: Path, seed: Path, starter: str) -> str:
    """Never overwrite a human-maintained document; create it only if missing."""
    if dest.exists():
        return "kept (human-maintained)"
    dest.parent.mkdir(parents=True, exist_ok=True)
    if seed.exists():
        dest.write_text(seed.read_text(encoding="utf-8"), encoding="utf-8")
        return "created from clm-lib seed (now owned by the results repository)"
    dest.write_text(starter, encoding="utf-8")
    return "created starter"


def _seed_root(dest_root: Path) -> str:
    """The root README is hand-maintained in the results repository; starter only if missing."""
    path = dest_root / "README.md"
    if path.exists():
        return "kept (human-maintained)"
    path.write_text(ROOT_STARTER, encoding="utf-8")
    return "created starter"


ROOT_STARTER = """# clm-lib test results

Experiment evidence exported from [clm-lib](https://github.com/armalite/clm-lib).

_Starter created by clm-lib export. This README is maintained by hand in this repository: add a
short summary and link for each experiment under `experiments/`._

See [EXPORT_FORMAT.md](EXPORT_FORMAT.md) for the folder layout and checksum policy.
"""

EXPORT_FORMAT_DOC = """# Export format

_Generated by `clm-lib export`; do not edit (it is rewritten on every export)._

## Who owns what

| Files | Owner | Export behaviour |
| --- | --- | --- |
| `README.md` (root), `experiments/<id>/README.md`, `SUMMARY.md`, `protocol.md` | this repository (hand-written) | never overwritten; a starter is created only if missing |
| `experiments/<id>/manifest.json`, `report.md`, `metrics.json`, `metrics.csv` | exporter (generated) | regenerated on every export |
| `experiments/<id>/artifacts/**` | exporter (immutable evidence) | written once; a differing copy is refused |
| `experiments/<id>/SHA256SUMS`, `EXPORT_FORMAT.md` | exporter (generated) | rewritten on every export |
| `ledger-snapshots/` | exporter (historical copies) | content-addressed; never overwritten |

Experiment selection (`experiment.json`: run ids, roles, settings, provenance) lives in clm-lib.
Write-ups, findings and historical protocols live here.

## Checksums

- **Immutable trees:** every run, fixture, comparison and source tree under `artifacts/` has its
  own `SHA256SUMS`. Re-exporting identical evidence is a no-op; different evidence under an
  existing name stops the export.
- **Experiment level:** `experiments/<id>/SHA256SUMS` covers `artifacts/**` and the generated
  files. It **excludes** the hand-written `README.md`, `SUMMARY.md` and `protocol.md`, so editing
  a write-up never looks like corrupted evidence. Before it is rewritten, its existing
  `artifacts/` entries are re-verified.
- **Verify:** run `sha256sum -c SHA256SUMS` inside a folder. Header lines starting with `#` are
  comments.

## Layout of an experiment folder

- `artifacts/runs/<role>/<run_id>/`: one run's evidence. Roles are:
  - `evaluation`: comparison runs;
  - `guided`: prompted demonstrations;
  - `calibration`: development runs;
  - `smoke` and `access-failure`: connectivity checks.

  Inside a run folder:
  - `run.json`: configuration;
  - `events.jsonl`: event log;
  - `requests/`: exact model requests (no headers);
  - `context/`: accepted context revisions and diffs;
  - `scripts/`: model-written code, saved before it ran;
  - `files/`: workspace files before and after each step;
  - `workspace/`: the final sandbox workspace;
  - `evaluator/`: truth and score, written after the run;
  - `summary.json`: metrics.
- `artifacts/fixtures/<task>/`: the task files, verified against each run's copy.
- `artifacts/comparisons/<stamp>/`: comparison records, frozen settings and source patches.
- `artifacts/source/`: provenance patches.

Run files are copied unchanged, except for the redactions listed in each `manifest.json`.
"""
