"""Results export: human documents are destination-owned, evidence is immutable."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import pytest

from clm_lib.export import ExportConflict, collect, export_experiment
from clm_lib.tasks import generate

from .conftest import FINAL, FakeExecutor, execute


def make_experiment(tmp_path: Path, run_ids: list[str], narrative: bool = False) -> Path:
    """An experiment definition: only experiment.json unless ``narrative`` seeds are wanted."""
    exp = tmp_path / "exp"
    exp.mkdir()
    spec = {
        "id": "999-test",
        "title": "test question",
        "runs": [{"run_id": r, "role": "evaluation"} for r in run_ids],
        "comparisons": [],
    }
    (exp / "experiment.json").write_text(json.dumps(spec))
    if narrative:
        (exp / "README.md").write_text("# seeded readme\n")
    return exp


@pytest.fixture
def exported(make_runner: Any, tmp_path: Path) -> dict[str, Any]:
    runner, _ = make_runner([execute("a"), FINAL], executor=FakeExecutor())
    res = runner.run(generate("dev"), "clm")
    exp = make_experiment(tmp_path, [res.run_id])
    dest = tmp_path / "results"
    log = export_experiment(exp, res.run_dir.parent, tmp_path / "ledger.json", dest)
    out = dest / "experiments" / "999-test"
    return {"res": res, "exp": exp, "dest": dest, "out": out, "log": log, "tmp": tmp_path}


def again(e: dict[str, Any]) -> dict[str, Any]:
    return export_experiment(e["exp"], e["res"].run_dir.parent, e["tmp"] / "ledger.json", e["dest"])


def tree_hashes(root: Path) -> dict[str, str]:
    return {
        str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


def test_new_experiment_exports_without_narrative_sources(exported: dict[str, Any]) -> None:
    out, dest, log = exported["out"], exported["dest"], exported["log"]
    for doc in ("README.md", "SUMMARY.md", "protocol.md"):
        assert log["documents"][doc] == "created starter"
        assert "Starter created by clm-lib export" in (out / doc).read_text()
    assert log["documents"]["root README.md"] == "created starter"
    assert (dest / "EXPORT_FORMAT.md").exists()
    assert log["warnings"] == ["root README.md does not mention 999-test; add a summary/link"]
    run_out = out / "artifacts" / "runs" / "evaluation" / exported["res"].run_id
    assert "fixtures" not in {p.name for p in run_out.iterdir()}
    manifest = json.loads((out / "manifest.json").read_text())
    assert manifest["runs"][0]["fixtures_match_generator"] is True
    assert set(manifest["documents"]["human_maintained"]) == {
        "README.md",
        "SUMMARY.md",
        "protocol.md",
    }


def test_human_documents_survive_export_and_are_not_checksummed(exported: dict[str, Any]) -> None:
    out, dest = exported["out"], exported["dest"]
    texts = {
        out / "README.md": "# My write-up\nFindings written by a person.\n",
        out / "SUMMARY.md": "### [999-test](experiments/999-test/README.md)\nhand summary\n",
        out / "protocol.md": "# Historical protocol\n",
        dest / "README.md": "# Hand-written index\n- 999-test\n",
    }
    for path, text in texts.items():
        path.write_text(text)
    log = again(exported)
    for path, text in texts.items():
        assert path.read_text() == text  # untouched
    assert all(v == "kept (human-maintained)" for v in log["documents"].values())
    assert log["warnings"] == []
    sums = (out / "SHA256SUMS").read_text()
    assert sums.startswith("# Generated by clm-lib export")
    listed = {
        line.split("  ", 1)[1] for line in sums.splitlines() if line and not line.startswith("#")
    }
    assert not listed & {"README.md", "SUMMARY.md", "protocol.md"}
    assert {"manifest.json", "report.md", "metrics.json", "metrics.csv"} <= listed
    # Editing a write-up again is still fine.
    (out / "README.md").write_text("# edited again\n")
    again(exported)
    assert (out / "README.md").read_text() == "# edited again\n"


def test_repeated_exports_preserve_identical_evidence(exported: dict[str, Any]) -> None:
    out = exported["out"]
    raw = tree_hashes(exported["res"].run_dir)
    before = tree_hashes(out)
    log = again(exported)
    assert set(log["runs"].values()) == {"unchanged"} and log["fixtures"]["dev"] == "unchanged"
    assert tree_hashes(out) == before
    assert tree_hashes(exported["res"].run_dir) == raw  # source run never modified


def test_conflicting_evidence_is_rejected(exported: dict[str, Any]) -> None:
    run_out = exported["out"] / "artifacts" / "runs" / "evaluation" / exported["res"].run_id
    # 1. A different run tree under the same id (tree checksum differs) is refused.
    original = (run_out / "SHA256SUMS").read_text()
    (run_out / "SHA256SUMS").write_text("tampered\n")
    # Caught by the pre-flight check of recorded evidence (or by the tree comparison).
    with pytest.raises(ExportConflict, match=r"no longer matches|refusing to overwrite evidence"):
        again(exported)
    (run_out / "SHA256SUMS").write_text(original)
    # 2. A silently edited artifact (tree checksum left as is) is caught by the
    #    experiment-level checksum, not accepted to make the export succeed.
    (run_out / "summary.json").write_text("{}")
    with pytest.raises(ExportConflict, match="no longer matches its recorded checksum"):
        again(exported)


def test_seed_documents_are_used_only_when_destination_lacks_them(
    make_runner: Any, tmp_path: Path
) -> None:
    runner, _ = make_runner([execute("a"), FINAL], executor=FakeExecutor())
    res = runner.run(generate("dev"), "clm")
    exp = make_experiment(tmp_path, [res.run_id], narrative=True)
    dest = tmp_path / "results"
    log = export_experiment(exp, res.run_dir.parent, tmp_path / "ledger.json", dest)
    out = dest / "experiments" / "999-test"
    assert log["documents"]["README.md"].startswith("created from clm-lib seed")
    (out / "README.md").write_text("# owned by results repo now\n")
    (exp / "README.md").write_text("# a later clm-lib edit must not leak over\n")
    export_experiment(exp, res.run_dir.parent, tmp_path / "ledger.json", dest)
    assert (out / "README.md").read_text() == "# owned by results repo now\n"


def test_export_redacts_local_uid(tmp_path: Path) -> None:
    run = tmp_path / "r"
    run.mkdir()
    (run / "run.json").write_text(json.dumps({"executor": {"user": "1000:1000 (non-root)"}}))
    (run / "fixtures").mkdir()
    (run / "fixtures" / "x").write_text("x")
    files = collect(run, skip_top=frozenset({"fixtures"}))
    assert set(files) == {"run.json"}
    assert "1000:1000" not in files["run.json"].decode()


def test_deleted_artifact_with_intact_checksums_is_rejected(exported: dict[str, Any]) -> None:
    out = exported["out"]
    run_out = out / "artifacts" / "runs" / "evaluation" / exported["res"].run_id
    victim = run_out / "events.jsonl"
    assert victim.is_file()
    victim.chmod(0o644)
    victim.unlink()  # both the run's and the experiment's SHA256SUMS still list it
    protected = [
        out / "SHA256SUMS",
        run_out / "SHA256SUMS",
        out / "manifest.json",
        out / "report.md",
        out / "metrics.json",
        out / "metrics.csv",
    ]
    before = {p: p.read_bytes() for p in protected}
    with pytest.raises(ExportConflict, match="is missing"):
        again(exported)
    # Previous checksum records and generated outputs are left exactly as they were.
    assert {p: p.read_bytes() for p in protected} == before
    assert not victim.exists()  # not silently restored either


def test_write_tree_checks_files_on_disk_not_just_the_checksum_list(tmp_path: Path) -> None:
    from clm_lib.export import write_tree

    files = {"a.txt": b"alpha", "sub/b.txt": b"beta"}
    dest = tmp_path / "tree"
    assert write_tree(dest, files) == "written"
    assert write_tree(dest, files) == "unchanged"
    with pytest.raises(ExportConflict, match="refusing to overwrite evidence"):
        write_tree(dest, {**files, "a.txt": b"different"})
    (dest / "sub" / "b.txt").unlink()
    with pytest.raises(ExportConflict, match="is missing"):
        write_tree(dest, files)
    (dest / "sub" / "b.txt").write_bytes(b"BETA")
    with pytest.raises(ExportConflict, match="no longer matches"):
        write_tree(dest, files)
    (dest / "sub" / "b.txt").write_bytes(b"beta")
    (dest / "extra.txt").write_bytes(b"x")
    with pytest.raises(ExportConflict, match="unrecorded files"):
        write_tree(dest, files)


def test_manifest_reports_the_scorer_of_the_exported_tasks(
    make_runner: Any, tmp_path: Path
) -> None:
    """Regression: coding experiments were exported with the incident scorer (score/2)."""
    coding_runner, _ = make_runner(
        [{"action": "advance"}] * 3 + [{"action": "final", "answer": {"summary": "x"}}],
        executor=FakeExecutor(),
    )
    coding = coding_runner.run(generate("coding-dev-1"), "clm")
    incident_runner, _ = make_runner([execute("a"), FINAL], executor=FakeExecutor())
    incident = incident_runner.run(generate("dev"), "clm")
    runs_root = coding.run_dir.parent
    assert incident.run_dir.parent == runs_root

    def manifest(run_ids: list[str], name: str) -> dict[str, Any]:
        exp = tmp_path / name
        exp.mkdir()
        spec = {
            "id": name,
            "title": "t",
            "runs": [{"run_id": r, "role": "evaluation"} for r in run_ids],
            "comparisons": [],
        }
        (exp / "experiment.json").write_text(json.dumps(spec))
        export_experiment(exp, runs_root, tmp_path / "ledger.json", tmp_path / "results")
        out = tmp_path / "results" / "experiments" / name
        return json.loads((out / "manifest.json").read_text())

    only_coding = manifest([coding.run_id], "998-coding")
    assert only_coding["exported_with"]["current_scorer"] == "invoice-checks/1"
    mixed = manifest([coding.run_id, incident.run_id], "997-mixed")
    assert mixed["exported_with"]["current_scorer"] == ["invoice-checks/1", "score/2"]
    assert (
        manifest([incident.run_id], "996-incident")["exported_with"]["current_scorer"] == "score/2"
    )
